# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plate_recognition.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plate_recognition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17plate_recognition.proto\x12\x05plate\"3\n\x0bPathRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x10\n\x08pipeline\x18\x02 \x01(\t\"4\n\x0c\x42ytesRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08pipeline\x18\x02 \x01(\t\"\x1e\n\rPlateResponse\x12\r\n\x05plate\x18\x01 \x01(\t2\x92\x01\n\x10PlateRecognition\x12=\n\x11RecognizeFromPath\x12\x12.plate.PathRequest\x1a\x14.plate.PlateResponse\x12?\n\x12RecognizeFromBytes\x12\x13.plate.BytesRequest\x1a\x14.plate.PlateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plate_recognition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATHREQUEST']._serialized_start=34
  _globals['_PATHREQUEST']._serialized_end=85
  _globals['_BYTESREQUEST']._serialized_start=87
  _globals['_BYTESREQUEST']._serialized_end=139
  _globals['_PLATERESPONSE']._serialized_start=141
  _globals['_PLATERESPONSE']._serialized_end=171
  _globals['_PLATERECOGNITION']._serialized_start=174
  _globals['_PLATERECOGNITION']._serialized_end=320
# @@protoc_insertion_point(module_scope)
