# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import plate_recognition_pb2 as plate__recognition__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plate_recognition_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlateRecognitionStub(object):
    """Number plate text extraction from images.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeFromPath = channel.unary_unary(
                '/plate.PlateRecognition/RecognizeFromPath',
                request_serializer=plate__recognition__pb2.PathRequest.SerializeToString,
                response_deserializer=plate__recognition__pb2.PlateResponse.FromString,
                _registered_method=True)
        self.RecognizeFromBytes = channel.unary_unary(
                '/plate.PlateRecognition/RecognizeFromBytes',
                request_serializer=plate__recognition__pb2.BytesRequest.SerializeToString,
                response_deserializer=plate__recognition__pb2.PlateResponse.FromString,
                _registered_method=True)


class PlateRecognitionServicer(object):
    """Number plate text extraction from images.
    """

    def RecognizeFromPath(self, request, context):
        """Reads an image from a path on the server filesystem.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFromBytes(self, request, context):
        """Decodes image bytes (e.g. JPEG/PNG file contents).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlateRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeFromPath': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFromPath,
                    request_deserializer=plate__recognition__pb2.PathRequest.FromString,
                    response_serializer=plate__recognition__pb2.PlateResponse.SerializeToString,
            ),
            'RecognizeFromBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFromBytes,
                    request_deserializer=plate__recognition__pb2.BytesRequest.FromString,
                    response_serializer=plate__recognition__pb2.PlateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plate.PlateRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plate.PlateRecognition', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlateRecognition(object):
    """Number plate text extraction from images.
    """

    @staticmethod
    def RecognizeFromPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plate.PlateRecognition/RecognizeFromPath',
            plate__recognition__pb2.PathRequest.SerializeToString,
            plate__recognition__pb2.PlateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeFromBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plate.PlateRecognition/RecognizeFromBytes',
            plate__recognition__pb2.BytesRequest.SerializeToString,
            plate__recognition__pb2.PlateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
